name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build_and_push_multiarch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date in UTC+8
        id: date
        run: |
          current_date=$(TZ="Asia/Shanghai" date +'%Y%m%d')
          echo "Current date is $current_date"
          echo "DATE=$current_date" >> $GITHUB_ENV

      - name: Build and push multi-arch Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t erstt/baidunetdisk:${{ env.DATE }} \
            -t erstt/baidunetdisk:latest \
            --push \
            .
